# Generated by Django 3.1.2 on 2020-11-03 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20201103_1102'),
    ]

    operations = [
        migrations.AddField(
            model_name='posts',
            name='image',
            field=models.ImageField(default='default.jpg', upload_to='post_pic'),
        ),
    ]
