# Generated by Django 3.1.3 on 2020-12-29 02:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_posts_likes'),
    ]

    operations = [
        migrations.DeleteModel(
            name='comments',
        ),
    ]
