# Generated by Django 3.1.3 on 2020-12-14 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0013_friend_request'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='request',
            field=models.ManyToManyField(blank=True, related_name='_profile_request_+', to='user.profile'),
        ),
    ]
