# Generated by Django 3.1.3 on 2020-12-15 03:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0014_profile_request'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='following',
        ),
    ]
